// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: inx.proto

package inx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerUpdate_Marker_MarkerType int32

const (
	LedgerUpdate_Marker_BEGIN LedgerUpdate_Marker_MarkerType = 0
	LedgerUpdate_Marker_END   LedgerUpdate_Marker_MarkerType = 1
)

// Enum value maps for LedgerUpdate_Marker_MarkerType.
var (
	LedgerUpdate_Marker_MarkerType_name = map[int32]string{
		0: "BEGIN",
		1: "END",
	}
	LedgerUpdate_Marker_MarkerType_value = map[string]int32{
		"BEGIN": 0,
		"END":   1,
	}
)

func (x LedgerUpdate_Marker_MarkerType) Enum() *LedgerUpdate_Marker_MarkerType {
	p := new(LedgerUpdate_Marker_MarkerType)
	*p = x
	return p
}

func (x LedgerUpdate_Marker_MarkerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerUpdate_Marker_MarkerType) Descriptor() protoreflect.EnumDescriptor {
	return file_inx_proto_enumTypes[0].Descriptor()
}

func (LedgerUpdate_Marker_MarkerType) Type() protoreflect.EnumType {
	return &file_inx_proto_enumTypes[0]
}

func (x LedgerUpdate_Marker_MarkerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerUpdate_Marker_MarkerType.Descriptor instead.
func (LedgerUpdate_Marker_MarkerType) EnumDescriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{28, 0, 0}
}

type NoParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParams) Reset() {
	*x = NoParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParams) ProtoMessage() {}

func (x *NoParams) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParams.ProtoReflect.Descriptor instead.
func (*NoParams) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{0}
}

// Node
type NodeConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseToken          *BaseToken               `protobuf:"bytes,1,opt,name=base_token,json=baseToken,proto3" json:"base_token,omitempty"`
	ProtocolParameters []*RawProtocolParameters `protobuf:"bytes,2,rep,name=protocol_parameters,json=protocolParameters,proto3" json:"protocol_parameters,omitempty"`
}

func (x *NodeConfiguration) Reset() {
	*x = NodeConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfiguration) ProtoMessage() {}

func (x *NodeConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfiguration.ProtoReflect.Descriptor instead.
func (*NodeConfiguration) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{1}
}

func (x *NodeConfiguration) GetBaseToken() *BaseToken {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *NodeConfiguration) GetProtocolParameters() []*RawProtocolParameters {
	if x != nil {
		return x.ProtocolParameters
	}
	return nil
}

type BaseToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TickerSymbol    string `protobuf:"bytes,2,opt,name=ticker_symbol,json=tickerSymbol,proto3" json:"ticker_symbol,omitempty"`
	Unit            string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Subunit         string `protobuf:"bytes,4,opt,name=subunit,proto3" json:"subunit,omitempty"`
	Decimals        uint32 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	UseMetricPrefix bool   `protobuf:"varint,6,opt,name=use_metric_prefix,json=useMetricPrefix,proto3" json:"use_metric_prefix,omitempty"`
}

func (x *BaseToken) Reset() {
	*x = BaseToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseToken) ProtoMessage() {}

func (x *BaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseToken.ProtoReflect.Descriptor instead.
func (*BaseToken) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{2}
}

func (x *BaseToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseToken) GetTickerSymbol() string {
	if x != nil {
		return x.TickerSymbol
	}
	return ""
}

func (x *BaseToken) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *BaseToken) GetSubunit() string {
	if x != nil {
		return x.Subunit
	}
	return ""
}

func (x *BaseToken) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *BaseToken) GetUseMetricPrefix() bool {
	if x != nil {
		return x.UseMetricPrefix
	}
	return false
}

type NodeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsHealthy              bool        `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	IsSynced               bool        `protobuf:"varint,2,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	IsAlmostSynced         bool        `protobuf:"varint,3,opt,name=is_almost_synced,json=isAlmostSynced,proto3" json:"is_almost_synced,omitempty"`
	LastAcceptedBlockSlot  uint64      `protobuf:"varint,4,opt,name=last_accepted_block_slot,json=lastAcceptedBlockSlot,proto3" json:"last_accepted_block_slot,omitempty"`
	LastConfirmedBlockSlot uint64      `protobuf:"varint,5,opt,name=last_confirmed_block_slot,json=lastConfirmedBlockSlot,proto3" json:"last_confirmed_block_slot,omitempty"`
	LatestCommitment       *Commitment `protobuf:"bytes,6,opt,name=latest_commitment,json=latestCommitment,proto3" json:"latest_commitment,omitempty"`
	LatestFinalizedSlot    uint64      `protobuf:"varint,7,opt,name=latest_finalized_slot,json=latestFinalizedSlot,proto3" json:"latest_finalized_slot,omitempty"`
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *NodeStatus) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

func (x *NodeStatus) GetIsAlmostSynced() bool {
	if x != nil {
		return x.IsAlmostSynced
	}
	return false
}

func (x *NodeStatus) GetLastAcceptedBlockSlot() uint64 {
	if x != nil {
		return x.LastAcceptedBlockSlot
	}
	return 0
}

func (x *NodeStatus) GetLastConfirmedBlockSlot() uint64 {
	if x != nil {
		return x.LastConfirmedBlockSlot
	}
	return 0
}

func (x *NodeStatus) GetLatestCommitment() *Commitment {
	if x != nil {
		return x.LatestCommitment
	}
	return nil
}

func (x *NodeStatus) GetLatestFinalizedSlot() uint64 {
	if x != nil {
		return x.LatestFinalizedSlot
	}
	return 0
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CooldownInMilliseconds uint32 `protobuf:"varint,1,opt,name=cooldown_in_milliseconds,json=cooldownInMilliseconds,proto3" json:"cooldown_in_milliseconds,omitempty"`
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{4}
}

func (x *NodeStatusRequest) GetCooldownInMilliseconds() uint32 {
	if x != nil {
		return x.CooldownInMilliseconds
	}
	return 0
}

type RawProtocolParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	StartEpoch      uint64 `protobuf:"varint,2,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	Params          []byte `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *RawProtocolParameters) Reset() {
	*x = RawProtocolParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawProtocolParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawProtocolParameters) ProtoMessage() {}

func (x *RawProtocolParameters) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawProtocolParameters.ProtoReflect.Descriptor instead.
func (*RawProtocolParameters) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{5}
}

func (x *RawProtocolParameters) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RawProtocolParameters) GetStartEpoch() uint64 {
	if x != nil {
		return x.StartEpoch
	}
	return 0
}

func (x *RawProtocolParameters) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

// Commitments
type RawCommitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RawCommitment) Reset() {
	*x = RawCommitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCommitment) ProtoMessage() {}

func (x *RawCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCommitment.ProtoReflect.Descriptor instead.
func (*RawCommitment) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{6}
}

func (x *RawCommitment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitmentId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CommitmentId) Reset() {
	*x = CommitmentId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitmentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentId) ProtoMessage() {}

func (x *CommitmentId) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentId.ProtoReflect.Descriptor instead.
func (*CommitmentId) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{7}
}

func (x *CommitmentId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type CommitmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitmentIndex uint64        `protobuf:"varint,1,opt,name=commitment_index,json=commitmentIndex,proto3" json:"commitment_index,omitempty"`
	CommitmentId    *CommitmentId `protobuf:"bytes,2,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
}

func (x *CommitmentRequest) Reset() {
	*x = CommitmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentRequest) ProtoMessage() {}

func (x *CommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentRequest.ProtoReflect.Descriptor instead.
func (*CommitmentRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{8}
}

func (x *CommitmentRequest) GetCommitmentIndex() uint64 {
	if x != nil {
		return x.CommitmentIndex
	}
	return 0
}

func (x *CommitmentRequest) GetCommitmentId() *CommitmentId {
	if x != nil {
		return x.CommitmentId
	}
	return nil
}

type SlotRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// start_slot is the initial slot to get. Use 0 to start from the current node status.
	StartSlot uint64 `protobuf:"varint,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty"`
	// end_slot is the last slot to get (inclusive). Use 0 to keep getting new confirmed slots.
	EndSlot uint64 `protobuf:"varint,2,opt,name=end_slot,json=endSlot,proto3" json:"end_slot,omitempty"`
}

func (x *SlotRangeRequest) Reset() {
	*x = SlotRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRangeRequest) ProtoMessage() {}

func (x *SlotRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRangeRequest.ProtoReflect.Descriptor instead.
func (*SlotRangeRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{9}
}

func (x *SlotRangeRequest) GetStartSlot() uint64 {
	if x != nil {
		return x.StartSlot
	}
	return 0
}

func (x *SlotRangeRequest) GetEndSlot() uint64 {
	if x != nil {
		return x.EndSlot
	}
	return 0
}

type Commitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitmentId *CommitmentId  `protobuf:"bytes,1,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
	Commitment   *RawCommitment `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (x *Commitment) Reset() {
	*x = Commitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commitment) ProtoMessage() {}

func (x *Commitment) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commitment.ProtoReflect.Descriptor instead.
func (*Commitment) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{10}
}

func (x *Commitment) GetCommitmentId() *CommitmentId {
	if x != nil {
		return x.CommitmentId
	}
	return nil
}

func (x *Commitment) GetCommitment() *RawCommitment {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type CommitmentAndProtocolParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment                *Commitment            `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	CurrentProtocolParameters *RawProtocolParameters `protobuf:"bytes,2,opt,name=current_protocol_parameters,json=currentProtocolParameters,proto3" json:"current_protocol_parameters,omitempty"`
}

func (x *CommitmentAndProtocolParameters) Reset() {
	*x = CommitmentAndProtocolParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitmentAndProtocolParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentAndProtocolParameters) ProtoMessage() {}

func (x *CommitmentAndProtocolParameters) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentAndProtocolParameters.ProtoReflect.Descriptor instead.
func (*CommitmentAndProtocolParameters) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{11}
}

func (x *CommitmentAndProtocolParameters) GetCommitment() *Commitment {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *CommitmentAndProtocolParameters) GetCurrentProtocolParameters() *RawProtocolParameters {
	if x != nil {
		return x.CurrentProtocolParameters
	}
	return nil
}

// Blocks
type RawBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RawBlock) Reset() {
	*x = RawBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawBlock) ProtoMessage() {}

func (x *RawBlock) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawBlock.ProtoReflect.Descriptor instead.
func (*RawBlock) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{12}
}

func (x *RawBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BlockId) Reset() {
	*x = BlockId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockId) ProtoMessage() {}

func (x *BlockId) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockId.ProtoReflect.Descriptor instead.
func (*BlockId) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{13}
}

func (x *BlockId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId *BlockId  `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Block   *RawBlock `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{14}
}

func (x *Block) GetBlockId() *BlockId {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *Block) GetBlock() *RawBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type BlockWithMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *BlockMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Block    *RawBlock      `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *BlockWithMetadata) Reset() {
	*x = BlockWithMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockWithMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockWithMetadata) ProtoMessage() {}

func (x *BlockWithMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockWithMetadata.ProtoReflect.Descriptor instead.
func (*BlockWithMetadata) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{15}
}

func (x *BlockWithMetadata) GetMetadata() *BlockMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockWithMetadata) GetBlock() *RawBlock {
	if x != nil {
		return x.Block
	}
	return nil
}

type BlockMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId   *BlockId `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Accepted  bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Confirmed bool     `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Finalized bool     `protobuf:"varint,4,opt,name=finalized,proto3" json:"finalized,omitempty"`
}

func (x *BlockMetadata) Reset() {
	*x = BlockMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMetadata) ProtoMessage() {}

func (x *BlockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMetadata.ProtoReflect.Descriptor instead.
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{16}
}

func (x *BlockMetadata) GetBlockId() *BlockId {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *BlockMetadata) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BlockMetadata) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *BlockMetadata) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

// Tips
type TipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count         uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	AllowSemiLazy bool   `protobuf:"varint,2,opt,name=allow_semiLazy,json=allowSemiLazy,proto3" json:"allow_semiLazy,omitempty"`
}

func (x *TipsRequest) Reset() {
	*x = TipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipsRequest) ProtoMessage() {}

func (x *TipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipsRequest.ProtoReflect.Descriptor instead.
func (*TipsRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{17}
}

func (x *TipsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TipsRequest) GetAllowSemiLazy() bool {
	if x != nil {
		return x.AllowSemiLazy
	}
	return false
}

type TipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tips []*BlockId `protobuf:"bytes,1,rep,name=tips,proto3" json:"tips,omitempty"`
}

func (x *TipsResponse) Reset() {
	*x = TipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipsResponse) ProtoMessage() {}

func (x *TipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipsResponse.ProtoReflect.Descriptor instead.
func (*TipsResponse) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{18}
}

func (x *TipsResponse) GetTips() []*BlockId {
	if x != nil {
		return x.Tips
	}
	return nil
}

type TipsMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntervalInMilliseconds uint32 `protobuf:"varint,1,opt,name=interval_in_milliseconds,json=intervalInMilliseconds,proto3" json:"interval_in_milliseconds,omitempty"`
}

func (x *TipsMetricRequest) Reset() {
	*x = TipsMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipsMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipsMetricRequest) ProtoMessage() {}

func (x *TipsMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipsMetricRequest.ProtoReflect.Descriptor instead.
func (*TipsMetricRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{19}
}

func (x *TipsMetricRequest) GetIntervalInMilliseconds() uint32 {
	if x != nil {
		return x.IntervalInMilliseconds
	}
	return 0
}

type TipsMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NonLazyPoolSize  uint32 `protobuf:"varint,1,opt,name=non_lazy_pool_size,json=nonLazyPoolSize,proto3" json:"non_lazy_pool_size,omitempty"`
	SemiLazyPoolSize uint32 `protobuf:"varint,2,opt,name=semi_lazy_pool_size,json=semiLazyPoolSize,proto3" json:"semi_lazy_pool_size,omitempty"`
}

func (x *TipsMetric) Reset() {
	*x = TipsMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipsMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipsMetric) ProtoMessage() {}

func (x *TipsMetric) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipsMetric.ProtoReflect.Descriptor instead.
func (*TipsMetric) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{20}
}

func (x *TipsMetric) GetNonLazyPoolSize() uint32 {
	if x != nil {
		return x.NonLazyPoolSize
	}
	return 0
}

func (x *TipsMetric) GetSemiLazyPoolSize() uint32 {
	if x != nil {
		return x.SemiLazyPoolSize
	}
	return 0
}

// UTXO
type TransactionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TransactionId) Reset() {
	*x = TransactionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionId) ProtoMessage() {}

func (x *TransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionId.ProtoReflect.Descriptor instead.
func (*TransactionId) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{21}
}

func (x *TransactionId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type OutputId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OutputId) Reset() {
	*x = OutputId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputId) ProtoMessage() {}

func (x *OutputId) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputId.ProtoReflect.Descriptor instead.
func (*OutputId) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{22}
}

func (x *OutputId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type OutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestCommitmentId *CommitmentId `protobuf:"bytes,1,opt,name=latest_commitment_id,json=latestCommitmentId,proto3" json:"latest_commitment_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*OutputResponse_Output
	//	*OutputResponse_Spent
	Payload isOutputResponse_Payload `protobuf_oneof:"payload"`
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{23}
}

func (x *OutputResponse) GetLatestCommitmentId() *CommitmentId {
	if x != nil {
		return x.LatestCommitmentId
	}
	return nil
}

func (m *OutputResponse) GetPayload() isOutputResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *OutputResponse) GetOutput() *LedgerOutput {
	if x, ok := x.GetPayload().(*OutputResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *OutputResponse) GetSpent() *LedgerSpent {
	if x, ok := x.GetPayload().(*OutputResponse_Spent); ok {
		return x.Spent
	}
	return nil
}

type isOutputResponse_Payload interface {
	isOutputResponse_Payload()
}

type OutputResponse_Output struct {
	Output *LedgerOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type OutputResponse_Spent struct {
	Spent *LedgerSpent `protobuf:"bytes,3,opt,name=spent,proto3,oneof"`
}

func (*OutputResponse_Output) isOutputResponse_Payload() {}

func (*OutputResponse_Spent) isOutputResponse_Payload() {}

type UnspentOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestCommitmentId *CommitmentId `protobuf:"bytes,1,opt,name=latest_commitment_id,json=latestCommitmentId,proto3" json:"latest_commitment_id,omitempty"`
	Output             *LedgerOutput `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *UnspentOutput) Reset() {
	*x = UnspentOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnspentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnspentOutput) ProtoMessage() {}

func (x *UnspentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnspentOutput.ProtoReflect.Descriptor instead.
func (*UnspentOutput) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{24}
}

func (x *UnspentOutput) GetLatestCommitmentId() *CommitmentId {
	if x != nil {
		return x.LatestCommitmentId
	}
	return nil
}

func (x *UnspentOutput) GetOutput() *LedgerOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type RawOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RawOutput) Reset() {
	*x = RawOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawOutput) ProtoMessage() {}

func (x *RawOutput) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawOutput.ProtoReflect.Descriptor instead.
func (*RawOutput) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{25}
}

func (x *RawOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LedgerOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputId    *OutputId  `protobuf:"bytes,1,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	BlockId     *BlockId   `protobuf:"bytes,2,opt,name=blockId,proto3" json:"blockId,omitempty"`
	SlotBooked  uint64     `protobuf:"varint,3,opt,name=slot_booked,json=slotBooked,proto3" json:"slot_booked,omitempty"`
	SlotCreated uint64     `protobuf:"varint,4,opt,name=slot_created,json=slotCreated,proto3" json:"slot_created,omitempty"`
	Output      *RawOutput `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *LedgerOutput) Reset() {
	*x = LedgerOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerOutput) ProtoMessage() {}

func (x *LedgerOutput) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerOutput.ProtoReflect.Descriptor instead.
func (*LedgerOutput) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{26}
}

func (x *LedgerOutput) GetOutputId() *OutputId {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *LedgerOutput) GetBlockId() *BlockId {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *LedgerOutput) GetSlotBooked() uint64 {
	if x != nil {
		return x.SlotBooked
	}
	return 0
}

func (x *LedgerOutput) GetSlotCreated() uint64 {
	if x != nil {
		return x.SlotCreated
	}
	return 0
}

func (x *LedgerOutput) GetOutput() *RawOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type LedgerSpent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output             *LedgerOutput  `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	TransactionIdSpent *TransactionId `protobuf:"bytes,2,opt,name=transaction_id_spent,json=transactionIdSpent,proto3" json:"transaction_id_spent,omitempty"`
	SlotSpent          uint64         `protobuf:"varint,3,opt,name=slot_spent,json=slotSpent,proto3" json:"slot_spent,omitempty"`
}

func (x *LedgerSpent) Reset() {
	*x = LedgerSpent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerSpent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerSpent) ProtoMessage() {}

func (x *LedgerSpent) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerSpent.ProtoReflect.Descriptor instead.
func (*LedgerSpent) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{27}
}

func (x *LedgerSpent) GetOutput() *LedgerOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *LedgerSpent) GetTransactionIdSpent() *TransactionId {
	if x != nil {
		return x.TransactionIdSpent
	}
	return nil
}

func (x *LedgerSpent) GetSlotSpent() uint64 {
	if x != nil {
		return x.SlotSpent
	}
	return 0
}

type LedgerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//
	//	*LedgerUpdate_BatchMarker
	//	*LedgerUpdate_Consumed
	//	*LedgerUpdate_Created
	Op isLedgerUpdate_Op `protobuf_oneof:"op"`
}

func (x *LedgerUpdate) Reset() {
	*x = LedgerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerUpdate) ProtoMessage() {}

func (x *LedgerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerUpdate.ProtoReflect.Descriptor instead.
func (*LedgerUpdate) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{28}
}

func (m *LedgerUpdate) GetOp() isLedgerUpdate_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *LedgerUpdate) GetBatchMarker() *LedgerUpdate_Marker {
	if x, ok := x.GetOp().(*LedgerUpdate_BatchMarker); ok {
		return x.BatchMarker
	}
	return nil
}

func (x *LedgerUpdate) GetConsumed() *LedgerSpent {
	if x, ok := x.GetOp().(*LedgerUpdate_Consumed); ok {
		return x.Consumed
	}
	return nil
}

func (x *LedgerUpdate) GetCreated() *LedgerOutput {
	if x, ok := x.GetOp().(*LedgerUpdate_Created); ok {
		return x.Created
	}
	return nil
}

type isLedgerUpdate_Op interface {
	isLedgerUpdate_Op()
}

type LedgerUpdate_BatchMarker struct {
	BatchMarker *LedgerUpdate_Marker `protobuf:"bytes,1,opt,name=batch_marker,json=batchMarker,proto3,oneof"`
}

type LedgerUpdate_Consumed struct {
	Consumed *LedgerSpent `protobuf:"bytes,2,opt,name=consumed,proto3,oneof"`
}

type LedgerUpdate_Created struct {
	Created *LedgerOutput `protobuf:"bytes,3,opt,name=created,proto3,oneof"`
}

func (*LedgerUpdate_BatchMarker) isLedgerUpdate_Op() {}

func (*LedgerUpdate_Consumed) isLedgerUpdate_Op() {}

func (*LedgerUpdate_Created) isLedgerUpdate_Op() {}

// REST API
type APIRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route string `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Host  string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port  uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Path  string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *APIRouteRequest) Reset() {
	*x = APIRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRouteRequest) ProtoMessage() {}

func (x *APIRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRouteRequest.ProtoReflect.Descriptor instead.
func (*APIRouteRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{29}
}

func (x *APIRouteRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *APIRouteRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *APIRouteRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *APIRouteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type APIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path    string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body    []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{30}
}

func (x *APIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *APIRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type APIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body    []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{31}
}

func (x *APIResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *APIResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *APIResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type LedgerUpdate_Marker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot          uint64                         `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	MarkerType    LedgerUpdate_Marker_MarkerType `protobuf:"varint,2,opt,name=marker_type,json=markerType,proto3,enum=inx.LedgerUpdate_Marker_MarkerType" json:"marker_type,omitempty"`
	ConsumedCount uint32                         `protobuf:"varint,3,opt,name=consumed_count,json=consumedCount,proto3" json:"consumed_count,omitempty"`
	CreatedCount  uint32                         `protobuf:"varint,4,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
}

func (x *LedgerUpdate_Marker) Reset() {
	*x = LedgerUpdate_Marker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inx_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerUpdate_Marker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerUpdate_Marker) ProtoMessage() {}

func (x *LedgerUpdate_Marker) ProtoReflect() protoreflect.Message {
	mi := &file_inx_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerUpdate_Marker.ProtoReflect.Descriptor instead.
func (*LedgerUpdate_Marker) Descriptor() ([]byte, []int) {
	return file_inx_proto_rawDescGZIP(), []int{28, 0}
}

func (x *LedgerUpdate_Marker) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LedgerUpdate_Marker) GetMarkerType() LedgerUpdate_Marker_MarkerType {
	if x != nil {
		return x.MarkerType
	}
	return LedgerUpdate_Marker_BEGIN
}

func (x *LedgerUpdate_Marker) GetConsumedCount() uint32 {
	if x != nil {
		return x.ConsumedCount
	}
	return 0
}

func (x *LedgerUpdate_Marker) GetCreatedCount() uint32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

var File_inx_proto protoreflect.FileDescriptor

var file_inx_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x6e, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x6e, 0x78,
	0x22, 0x0a, 0x0a, 0x08, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x8f, 0x01, 0x0a,
	0x11, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x61, 0x73,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x4b, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0xba,
	0x01, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x75,
	0x6e, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12,
	0x2a, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xd8, 0x02, 0x0a, 0x0a,
	0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x69, 0x73, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x53, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6d,
	0x6f, 0x73, 0x74, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x69, 0x73, 0x41, 0x6c, 0x6d, 0x6f, 0x73, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x65, 0x64,
	0x12, 0x37, 0x0a, 0x18, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x15, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x39, 0x0a, 0x19, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x6c, 0x61,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x6c, 0x6f, 0x74, 0x12, 0x3c, 0x0a, 0x11, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x10, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x13, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x4d, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x63,
	0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x16, 0x63,
	0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x7b, 0x0a, 0x15, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x29,
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x61, 0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x76, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x36, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x4c, 0x0a, 0x10, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x6c, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x6c,
	0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x78, 0x0a,
	0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61,
	0x77, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5a, 0x0a, 0x1b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x19, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x19, 0x0a, 0x07, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x08,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x07, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x68, 0x0a, 0x11, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x2e, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x4a, 0x0a, 0x0b, 0x54, 0x69, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x6d, 0x69, 0x4c, 0x61, 0x7a, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x6d, 0x69, 0x4c,
	0x61, 0x7a, 0x79, 0x22, 0x30, 0x0a, 0x0c, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x52,
	0x04, 0x74, 0x69, 0x70, 0x73, 0x22, 0x4d, 0x0a, 0x11, 0x54, 0x69, 0x70, 0x73, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x18, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x16, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0x68, 0x0a, 0x0a, 0x54, 0x69, 0x70, 0x73, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x12, 0x2b, 0x0a, 0x12, 0x6e, 0x6f, 0x6e, 0x5f, 0x6c, 0x61, 0x7a, 0x79, 0x5f, 0x70,
	0x6f, 0x6f, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f,
	0x6e, 0x6f, 0x6e, 0x4c, 0x61, 0x7a, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x2d, 0x0a, 0x13, 0x73, 0x65, 0x6d, 0x69, 0x5f, 0x6c, 0x61, 0x7a, 0x79, 0x5f, 0x70, 0x6f, 0x6f,
	0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x65,
	0x6d, 0x69, 0x4c, 0x61, 0x7a, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x1f,
	0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1a, 0x0a, 0x08, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x0e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x14, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69,
	0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52,
	0x12, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x28, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7f, 0x0a, 0x0d, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x43, 0x0a, 0x14, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x12, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x52, 0x61, 0x77, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xce, 0x01, 0x0a, 0x0c, 0x4c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x64, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x64, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x6c, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x26, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x44, 0x0a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x6f,
	0x74, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73,
	0x6c, 0x6f, 0x74, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x22, 0x85, 0x03, 0x0a, 0x0c, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x78,
	0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x1a, 0xd0, 0x01, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x44, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70,
	0x22, 0x63, 0x0a, 0x0f, 0x41, 0x50, 0x49, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x36, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x3a, 0x0a, 0x0c,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xaa, 0x01, 0x0a, 0x0b, 0x41, 0x50, 0x49,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x69, 0x6e, 0x78, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xfc, 0x06, 0x0a, 0x03, 0x49, 0x4e, 0x58, 0x12, 0x30, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0f,
	0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3f, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x54, 0x6f, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x30, 0x01,
	0x12, 0x3e, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e,
	0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x16, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x39, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x6e, 0x78,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x54, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x0d, 0x2e,
	0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x69,
	0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x16, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x54, 0x6f, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x30,
	0x01, 0x12, 0x36, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x54, 0x6f, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x0d, 0x2e, 0x69,
	0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x0b, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52,
	0x61, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64,
	0x1a, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x52, 0x61, 0x77, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x35, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x0c, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x64, 0x1a, 0x12, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x55, 0x6e,
	0x73, 0x70, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x0d, 0x2e, 0x69,
	0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x12, 0x2e, 0x69, 0x6e,
	0x78, 0x2e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x30,
	0x01, 0x12, 0x43, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x54, 0x6f, 0x4c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x69, 0x6e, 0x78,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x41, 0x50, 0x49, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x69,
	0x6e, 0x78, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x39, 0x0a, 0x12, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x50, 0x49, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x41, 0x50,
	0x49, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x69, 0x6e, 0x78, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x36, 0x0a, 0x11,
	0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0f, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x69, 0x6e, 0x78, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x6f, 0x74, 0x61, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x78, 0x2f, 0x67, 0x6f, 0x3b, 0x69, 0x6e, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inx_proto_rawDescOnce sync.Once
	file_inx_proto_rawDescData = file_inx_proto_rawDesc
)

func file_inx_proto_rawDescGZIP() []byte {
	file_inx_proto_rawDescOnce.Do(func() {
		file_inx_proto_rawDescData = protoimpl.X.CompressGZIP(file_inx_proto_rawDescData)
	})
	return file_inx_proto_rawDescData
}

var file_inx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inx_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_inx_proto_goTypes = []interface{}{
	(LedgerUpdate_Marker_MarkerType)(0),     // 0: inx.LedgerUpdate.Marker.MarkerType
	(*NoParams)(nil),                        // 1: inx.NoParams
	(*NodeConfiguration)(nil),               // 2: inx.NodeConfiguration
	(*BaseToken)(nil),                       // 3: inx.BaseToken
	(*NodeStatus)(nil),                      // 4: inx.NodeStatus
	(*NodeStatusRequest)(nil),               // 5: inx.NodeStatusRequest
	(*RawProtocolParameters)(nil),           // 6: inx.RawProtocolParameters
	(*RawCommitment)(nil),                   // 7: inx.RawCommitment
	(*CommitmentId)(nil),                    // 8: inx.CommitmentId
	(*CommitmentRequest)(nil),               // 9: inx.CommitmentRequest
	(*SlotRangeRequest)(nil),                // 10: inx.SlotRangeRequest
	(*Commitment)(nil),                      // 11: inx.Commitment
	(*CommitmentAndProtocolParameters)(nil), // 12: inx.CommitmentAndProtocolParameters
	(*RawBlock)(nil),                        // 13: inx.RawBlock
	(*BlockId)(nil),                         // 14: inx.BlockId
	(*Block)(nil),                           // 15: inx.Block
	(*BlockWithMetadata)(nil),               // 16: inx.BlockWithMetadata
	(*BlockMetadata)(nil),                   // 17: inx.BlockMetadata
	(*TipsRequest)(nil),                     // 18: inx.TipsRequest
	(*TipsResponse)(nil),                    // 19: inx.TipsResponse
	(*TipsMetricRequest)(nil),               // 20: inx.TipsMetricRequest
	(*TipsMetric)(nil),                      // 21: inx.TipsMetric
	(*TransactionId)(nil),                   // 22: inx.TransactionId
	(*OutputId)(nil),                        // 23: inx.OutputId
	(*OutputResponse)(nil),                  // 24: inx.OutputResponse
	(*UnspentOutput)(nil),                   // 25: inx.UnspentOutput
	(*RawOutput)(nil),                       // 26: inx.RawOutput
	(*LedgerOutput)(nil),                    // 27: inx.LedgerOutput
	(*LedgerSpent)(nil),                     // 28: inx.LedgerSpent
	(*LedgerUpdate)(nil),                    // 29: inx.LedgerUpdate
	(*APIRouteRequest)(nil),                 // 30: inx.APIRouteRequest
	(*APIRequest)(nil),                      // 31: inx.APIRequest
	(*APIResponse)(nil),                     // 32: inx.APIResponse
	(*LedgerUpdate_Marker)(nil),             // 33: inx.LedgerUpdate.Marker
	nil,                                     // 34: inx.APIRequest.HeadersEntry
	nil,                                     // 35: inx.APIResponse.HeadersEntry
}
var file_inx_proto_depIdxs = []int32{
	3,  // 0: inx.NodeConfiguration.base_token:type_name -> inx.BaseToken
	6,  // 1: inx.NodeConfiguration.protocol_parameters:type_name -> inx.RawProtocolParameters
	11, // 2: inx.NodeStatus.latest_commitment:type_name -> inx.Commitment
	8,  // 3: inx.CommitmentRequest.commitment_id:type_name -> inx.CommitmentId
	8,  // 4: inx.Commitment.commitment_id:type_name -> inx.CommitmentId
	7,  // 5: inx.Commitment.commitment:type_name -> inx.RawCommitment
	11, // 6: inx.CommitmentAndProtocolParameters.commitment:type_name -> inx.Commitment
	6,  // 7: inx.CommitmentAndProtocolParameters.current_protocol_parameters:type_name -> inx.RawProtocolParameters
	14, // 8: inx.Block.block_id:type_name -> inx.BlockId
	13, // 9: inx.Block.block:type_name -> inx.RawBlock
	17, // 10: inx.BlockWithMetadata.metadata:type_name -> inx.BlockMetadata
	13, // 11: inx.BlockWithMetadata.block:type_name -> inx.RawBlock
	14, // 12: inx.BlockMetadata.block_id:type_name -> inx.BlockId
	14, // 13: inx.TipsResponse.tips:type_name -> inx.BlockId
	8,  // 14: inx.OutputResponse.latest_commitment_id:type_name -> inx.CommitmentId
	27, // 15: inx.OutputResponse.output:type_name -> inx.LedgerOutput
	28, // 16: inx.OutputResponse.spent:type_name -> inx.LedgerSpent
	8,  // 17: inx.UnspentOutput.latest_commitment_id:type_name -> inx.CommitmentId
	27, // 18: inx.UnspentOutput.output:type_name -> inx.LedgerOutput
	23, // 19: inx.LedgerOutput.output_id:type_name -> inx.OutputId
	14, // 20: inx.LedgerOutput.blockId:type_name -> inx.BlockId
	26, // 21: inx.LedgerOutput.output:type_name -> inx.RawOutput
	27, // 22: inx.LedgerSpent.output:type_name -> inx.LedgerOutput
	22, // 23: inx.LedgerSpent.transaction_id_spent:type_name -> inx.TransactionId
	33, // 24: inx.LedgerUpdate.batch_marker:type_name -> inx.LedgerUpdate.Marker
	28, // 25: inx.LedgerUpdate.consumed:type_name -> inx.LedgerSpent
	27, // 26: inx.LedgerUpdate.created:type_name -> inx.LedgerOutput
	34, // 27: inx.APIRequest.headers:type_name -> inx.APIRequest.HeadersEntry
	35, // 28: inx.APIResponse.headers:type_name -> inx.APIResponse.HeadersEntry
	0,  // 29: inx.LedgerUpdate.Marker.marker_type:type_name -> inx.LedgerUpdate.Marker.MarkerType
	1,  // 30: inx.INX.ReadNodeStatus:input_type -> inx.NoParams
	5,  // 31: inx.INX.ListenToNodeStatus:input_type -> inx.NodeStatusRequest
	1,  // 32: inx.INX.ReadNodeConfiguration:input_type -> inx.NoParams
	9,  // 33: inx.INX.ReadCommitment:input_type -> inx.CommitmentRequest
	1,  // 34: inx.INX.ListenToBlocks:input_type -> inx.NoParams
	1,  // 35: inx.INX.ListenToAcceptedBlocks:input_type -> inx.NoParams
	1,  // 36: inx.INX.ListenToConfirmedBlocks:input_type -> inx.NoParams
	13, // 37: inx.INX.SubmitBlock:input_type -> inx.RawBlock
	14, // 38: inx.INX.ReadBlock:input_type -> inx.BlockId
	14, // 39: inx.INX.ReadBlockMetadata:input_type -> inx.BlockId
	1,  // 40: inx.INX.ReadUnspentOutputs:input_type -> inx.NoParams
	10, // 41: inx.INX.ListenToLedgerUpdates:input_type -> inx.SlotRangeRequest
	23, // 42: inx.INX.ReadOutput:input_type -> inx.OutputId
	30, // 43: inx.INX.RegisterAPIRoute:input_type -> inx.APIRouteRequest
	30, // 44: inx.INX.UnregisterAPIRoute:input_type -> inx.APIRouteRequest
	31, // 45: inx.INX.PerformAPIRequest:input_type -> inx.APIRequest
	4,  // 46: inx.INX.ReadNodeStatus:output_type -> inx.NodeStatus
	4,  // 47: inx.INX.ListenToNodeStatus:output_type -> inx.NodeStatus
	2,  // 48: inx.INX.ReadNodeConfiguration:output_type -> inx.NodeConfiguration
	11, // 49: inx.INX.ReadCommitment:output_type -> inx.Commitment
	15, // 50: inx.INX.ListenToBlocks:output_type -> inx.Block
	15, // 51: inx.INX.ListenToAcceptedBlocks:output_type -> inx.Block
	15, // 52: inx.INX.ListenToConfirmedBlocks:output_type -> inx.Block
	14, // 53: inx.INX.SubmitBlock:output_type -> inx.BlockId
	13, // 54: inx.INX.ReadBlock:output_type -> inx.RawBlock
	17, // 55: inx.INX.ReadBlockMetadata:output_type -> inx.BlockMetadata
	25, // 56: inx.INX.ReadUnspentOutputs:output_type -> inx.UnspentOutput
	29, // 57: inx.INX.ListenToLedgerUpdates:output_type -> inx.LedgerUpdate
	24, // 58: inx.INX.ReadOutput:output_type -> inx.OutputResponse
	1,  // 59: inx.INX.RegisterAPIRoute:output_type -> inx.NoParams
	1,  // 60: inx.INX.UnregisterAPIRoute:output_type -> inx.NoParams
	32, // 61: inx.INX.PerformAPIRequest:output_type -> inx.APIResponse
	46, // [46:62] is the sub-list for method output_type
	30, // [30:46] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_inx_proto_init() }
func file_inx_proto_init() {
	if File_inx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawProtocolParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCommitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitmentId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitmentAndProtocolParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockWithMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipsMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipsMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnspentOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerSpent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inx_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerUpdate_Marker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inx_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*OutputResponse_Output)(nil),
		(*OutputResponse_Spent)(nil),
	}
	file_inx_proto_msgTypes[28].OneofWrappers = []interface{}{
		(*LedgerUpdate_BatchMarker)(nil),
		(*LedgerUpdate_Consumed)(nil),
		(*LedgerUpdate_Created)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inx_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inx_proto_goTypes,
		DependencyIndexes: file_inx_proto_depIdxs,
		EnumInfos:         file_inx_proto_enumTypes,
		MessageInfos:      file_inx_proto_msgTypes,
	}.Build()
	File_inx_proto = out.File
	file_inx_proto_rawDesc = nil
	file_inx_proto_goTypes = nil
	file_inx_proto_depIdxs = nil
}
