name: GolangCIlint

on:
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'proto/**'

jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ./go
          go_version_file: go/go.mod
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=10m"
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
